### ISSUE TITLE
Which MBTiles are compatible with Tangram ES?

### ISSUE THREAD

**Issue by carlos-mg89** [kueda/TangramAndroidMBTilesDemo#1]
Hello @kueda ,

First of all, I would like to thank you for the work you've done. I'm finding a little bit of hope for what I want to use Tangram, and in part is because of you.

I am able to run the project perfectly, and I have even played a bit with the YAML style and see it's effects on the app I'm running over the phone. However, I thought I'd be able to show a MBTile file I downloaded from https://openmaptiles.com , but had no luck at all.

Is there any place you know with already packed MBTiles that work with Tangram ES? Or could you at least point me towards the direction that I extract them from a PBF/OSM file, and pack them into a MBTile file?

I have been trying for a long time with very bad results. I want to load a preloaded file into an Android app.

Thanks in advance

**Comment by kueda** [comment]
Glad you're finding it useful! This repo actually has an MBtiles file that should work: https://github.com/kueda/TangramAndroidMBTilesDemo/blob/master/app/src/main/assets/tm_world_borders.mbtiles. However, I've also tested it with an export from https://openmaptiles.com and it works with that too. The main problems I've encountered are styling issues (i.e. knowing the names of the layers in your MBTiles file and styling accordingly) and the fact that the MBTiles can't be in the assets folder and must be copied to app storage on first app launch (see https://github.com/kueda/TangramAndroidMBTilesDemo/blob/master/app/src/main/java/com/mapzen/tangramandroidmbtilesdemo/MainActivity.java#L30). If you can paste in some of your error messages, stacktraces, or screenshots, I can take a look.

**Comment by carlos-mg89** [comment]
@kueda I'm struggling to make it work with MBTiles downloaded from openmaptiles.com, but I made it work with the MBTile generated with the instructions you provided:
`tl copy -z 0 -Z 5  omnivore:///absolute/path/to/TM_WORLD_BORDERS_SIMPL-0.3.shp mbtiles:///absolute/path/to/TangramAndroidMBTilesDemo/app/src/main/assets/tm_world_borders.mbtiles`

When I download an MBTiles from openmaptiles.com, for example, I tried with this one:
[https://openmaptiles.com/downloads/tileset/osm/europe/spain/barcelona/](url)
I just get a black screen. And I have moved the latitude and longitude to be over Barcelona, and with the world borders MBTiles I can see the coastline of Barcelona.

I have only changed the name of the MBTile file being loaded, and I get the toast with the message scene loaded.

I attached a txt with the logcat:
[error.txt](https://github.com/kueda/TangramAndroidMBTilesDemo/files/1582259/error.txt)

Apparently, there aren't any errors while loading the MBTile. Perhaps the scene.yaml that is being loaded doesn't match any of the contents inside of the MBTile I attached? I haven't changed the scene.yaml at all, except the name of the file to be loaded. barcelona.mbtiles

Yesterday I tried with other YAML, but it didn't work. I got the same result.

**Comment by kueda** [comment]
That sounds like an issue with your Tangram scene YAML. Here's a version of one that I have working in a different project (I copied and pasted most of this from somewhere else, unfortunately I don't recall where):

```yaml
import:
    - https://tangrams.github.io/blocks/filter/grain.yaml

scene:
    background:
        color: '#555'

sources:
    osm:
        type: MVT
        url: 'file:///storage/emulated/0/Android/data/com.mapzen.tangramandroidmbtilesdemo/path/to/your.mbtiles'
        max_zoom: 14

cameras:
    cam:
        type: flat

lights:
    dir:
        type: directional
        direction: [.1, .5, -1]
        diffuse: .7
        ambient: .5

layers:
    water:
        data:
            source: osm
            layer: water
        draw:
            water:
                order: 10
                color: [0.224, 0.224, 0.224, 1.00]
    waterway:
        data:
            source: osm
            layer: waterway
        draw:
            lines:
                order: 11
                color: '#353535'
                width: 1.3px
    landuse:
        data:
            source: osm
            layer: landuse
            filter:
                class: residential
        draw:
            landuse:
                order: 5
                color: [0.349, 0.349, 0.349, 1.00]
    park:
        data:
            source: osm
            layer: park
        draw:
            park:
                order: 5
                color: [0.290, 0.290, 0.290, 1.00]
    boundary:
        data:
            source: osm
            layer: boundary
        draw:
            lines:
                order: 30
                color: [1, 0, 0, 1.00]
                width: 2px
    transportation:
        data:
            source: osm
            layer: transportation
        draw:
            lines:
                order: 101
                color: [0.314, 0.314, 0.314, 1.00]
                width: 1.2px
styles:
    water:
        base: polygons
        mix: filter-grain
    vectile:
        base: polygons
        mix: filter-grain
    landuse:
        base: polygons
        mix: filter-grain
    park:
        base: polygons
        mix: filter-grain
    boundary:
        base: lines
```

The most important parts are getting that source path right and then knowing what the layer names are, like `landuse` and `park`. Those *should* be documented somewhere, but if not, you can figure them out by opening the MBTiles file in sqlite.
